// examples/07-react-basic/src/App.jsx
import { useState } from 'react'
import './style.css'

export default function App() {
  const [count, setCount] = useState(0)

  return (
    <main className="page">
      <section className="card">
        <h1>07. Vite + React</h1>
        <p>这是一个最小 React 示例。</p>
        <p>当前计数：<strong>{count}</strong></p>
        <button onClick={() => setCount(count + 1)}>+1</button>
      </section>
    </main>
  )
}

// examples/08-vue-basic/src/App.vue
<script setup>
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <main class="page">
    <section class="card">
      <h1>08. Vite + Vue</h1>
      <p>这是一个最小 Vue 示例。</p>
      <p>当前计数：<strong>{{ count }}</strong></p>
      <button @click="count++">+1</button>
    </section>
  </main>
</template>
